import { MessageSquareText, Sparkles, ArrowRight } from 'lucide-react';
import { Link } from 'react-router';
import { Button } from '@/components/ui/button';

/**
 * "Ask DMV" — intro/landing for the DMV Assistant. The live agent conversation
 * is the persistent inline experience on the "Apply for a New License" page
 * (/renew), which is the site's single Agentforce surface. This page introduces
 * it and routes the resident there. (Embedded Messaging's bootstrap is a
 * page-load singleton, so we intentionally keep ONE inline agent surface.)
 */
const SUGGESTIONS = [
  'What documents do I need to apply for a license?',
  'How much does a REAL ID cost?',
  'Am I eligible for a Class C license?',
  'Where is the nearest DMV office?',
];

export default function Assistant() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-14 sm:px-6 lg:px-8">
      <div className="text-center">
        <span className="inline-flex items-center gap-2 rounded-full bg-dmv-blue-10 px-3.5 py-1.5 text-xs font-medium text-dmv-blue">
          <Sparkles className="h-3.5 w-3.5" />
          DMV Virtual Assistant
        </span>
        <h1 className="mt-5 text-3xl font-bold text-dmv-navy sm:text-4xl">
          Ask DMV
        </h1>
        <p className="mx-auto mt-3 max-w-xl text-base leading-relaxed text-dmv-slate">
          Get instant answers about licenses, REAL ID, fees, appointments, and
          more — powered by Agentforce. Start a conversation and our virtual
          assistant will help you right away.
        </p>
        <div className="mt-8 flex justify-center">
          <Button asChild size="lg" className="gap-2">
            <Link to="/renew">
              <MessageSquareText className="h-4 w-4" />
              Start a conversation
            </Link>
          </Button>
        </div>
        <p className="mt-3 text-xs text-dmv-mist">
          The assistant guides you through your application, step by step.
        </p>
      </div>

      {/* Suggested prompts */}
      <div className="mt-14">
        <h2 className="mb-4 flex items-center justify-center gap-2 text-sm font-semibold text-dmv-navy">
          <MessageSquareText className="h-4 w-4 text-dmv-blue" />
          Popular questions
        </h2>
        <div className="grid gap-3 sm:grid-cols-2">
          {SUGGESTIONS.map(s => (
            <Link
              key={s}
              to="/renew"
              className="group flex items-center justify-between gap-3 rounded-xl border border-dmv-line bg-white p-4 text-left text-sm text-dmv-slate shadow-dmv-xs transition-all hover:-translate-y-0.5 hover:border-dmv-blue-20 hover:shadow-dmv-glow"
            >
              <span>{s}</span>
              <ArrowRight className="h-4 w-4 shrink-0 text-dmv-blue transition-transform group-hover:translate-x-0.5" />
            </Link>
          ))}
        </div>
      </div>

      <p className="mx-auto mt-12 max-w-xl text-center text-xs text-dmv-mist">
        Responses are generated by an AI assistant and may require verification
        for official transactions. For account-specific matters, you may be
        connected to a DMV representative.
      </p>
    </div>
  );
}
